hll_p: 4
cache_capacity: 2
token_bucket_reset_interval: 10
token_bucket_max_token_num: 10
cms_epsilon: 0.1
cms_delta: 0.1
memtable_threshold: 4
sl_max_level: 15
sl_probability: 0.5
wal_segment: 3
wal_low_mark: 2
false_positive_rate: 0.4
